filters:
  min_liquidity: 100
  require_mint_disabled: true

solana:
  rpc_endpoints:
    - "https://api.mainnet-beta.solana.com"
    - "https://rpc.ankr.com/solana"
    - "https://solana.publicnode.com"
  wss_endpoints:
    - "wss://api.mainnet-beta.solana.com"
    - "wss://solana.publicnode.com"

notifiers:
  wecom_webhook: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e9f4afa6-3b7b-4a60-b52a-f0155dbe7a77"
  discord_token: "MTUwNDc4MjczNDU5NjUwNTYwMA.GMHkzX.UoXye6iYsmKDtj4M3-j5tTib0_gXxu-2nvUy1w"
  discord_channel_id: ""

app:
  proxy: "http://127.0.0.1:10808"
